### ISSUE TITLE
reward 只能是负值？

### ISSUE THREAD

**Issue by harryhare** [zlslhp/reinforcement_tutorial#1]
1.reward 只能是负值？
2.初始时加的千分之几的随机数有什么用？
agent.q_value = agent.q_value + np.random.uniform(0, 1, size=transition.shape) / 1000
好像把这句注释掉，也可以得出一样的结果。

**Comment by davidz-zzz** [comment]
1. reward值是自定义的，在到达终点时的reward是正的。
2.随机数是让每个state上q值分布更为均匀。初始q值为0也可以，但是会影响state搜索的次数。
